-- 1
SELECT COUNT(E.EMP_NO), E.DEPT_NO
FROM EMPLE E
GROUP BY E.DEPT_NO;

-- 2 
SELECT COUNT(E.EMP_NO), E.DEPT_NO
FROM EMPLE E
GROUP BY E.DEPT_NO
HAVING COUNT(E.EMP_NO) > 5;

-- 3 
SELECT AVG(E.SALARIO), E.DEPT_NO
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO
GROUP BY E.DEPT_NO;

-- 4 
SELECT E.APELLIDO
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO AND D.DNOMBRE LIKE 'VENTAS' AND E.OFICIO LIKE 'VENDEDOR';

-- 5 
SELECT COUNT(E.APELLIDO)
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO AND D.DNOMBRE LIKE 'VENTAS' AND E.OFICIO LIKE 'VENDEDOR';

-- 6 
SELECT DISTINCT E.OFICIO
FROM EMPLE E, DEPART D
WHERE D.DNOMBRE LIKE 'VENTAS' AND D.DEPT_NO = E.DEPT_NO;

-- 7 
SELECT COUNT(E.DEPT_NO), D.DEPT_NO 
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO AND E.OFICIO LIKE 'EMPLEADO'
GROUP BY D.DEPT_NO;

-- 8  
SELECT COUNT(E.EMP_NO)
FROM EMPLE e 
GROUP BY E.DEPT_NO 
ORDER BY COUNT(E.EMP_NO) DESC LIMIT 1 ;

-- 9 
SELECT SUM(E.SALARIO), D.DEPT_NO
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO 
GROUP BY D.DEPT_NO 
HAVING SUM(E.SALARIO) > AVG(E.SALARIO);

-- 10
SELECT SUM(E.SALARIO), E.OFICIO
FROM EMPLE E
GROUP BY E.OFICIO;

-- 11 
SELECT SUM(E.SALARIO), E.OFICIO
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO AND D.DNOMBRE LIKE 'VENTAS'
GROUP BY E.OFICIO;

-- 12 
SELECT DEPART.DNOMBRE  
FROM DEPART , EMPLE
WHERE DEPART.DEPT_NO = EMPLE.DEPT_NO 
 AND EMPLE.OFICIO LIKE 'EMPLEADO'
GROUP BY DEPART.DEPT_NO
ORDER BY COUNT(EMPLE.EMP_NO) DESC LIMIT 1;

-- 13 --
SELECT COUNT(DISTINCT EMPLE.OFICIO), EMPLE.DEPT_NO 
FROM EMPLE 
GROUP BY EMPLE.DEPT_NO;

-- 14 --
SELECT DEPART.DEPT_NO 
FROM DEPART , EMPLE 
-- SIN TERMINAR --


-- 15 -- 
SELECT SUM(H.UNIDADES), H.ESTANTERIA
FROM HERRAMIENTAS H
GROUP BY H.ESTANTERIA;

-- 16 -- 
SELECT HERRAMIENTAS.ESTANTERIA , SUM(HERRAMIENTAS.UNIDADES) AS SUMA_UNIDADES
FROM HERRAMIENTAS 
GROUP BY HERRAMIENTAS.ESTANTERIA 
ORDER BY SUMA_UNIDADES DESC LIMIT 1;

-- 17 --
SELECT COUNT(MEDICOS.DNI)AS NUM_MEDICOS, HOSPITALES.COD_HOSPITAL 
FROM HOSPITALES, MEDICOS
WHERE HOSPITALES.COD_HOSPITAL = MEDICOS.COD_HOSPITAL 
GROUP BY HOSPITALES.COD_HOSPITAL 
ORDER BY HOSPITALES.COD_HOSPITAL DESC;

-- 18 -- 
SELECT DISTINCT HOSPITALES.NOMBRE, MEDICOS.ESPECIALIDAD
FROM HOSPITALES, MEDICOS
WHERE HOSPITALES.COD_HOSPITAL = MEDICOS.COD_HOSPITAL ;

-- 19 --
SELECT DISTINCT HOSPITALES.NOMBRE, MEDICOS.ESPECIALIDAD, COUNT(MEDICOS.DNI)
FROM HOSPITALES , MEDICOS 
WHERE HOSPITALES.COD_HOSPITAL = MEDICOS.COD_HOSPITAL 
GROUP BY HOSPITALES.NOMBRE , MEDICOS.ESPECIALIDAD ;

-- 20 --
SELECT COUNT(P.DNI), H.COD_HOSPITAL
FROM HOSPITALES H, PERSONAS P
WHERE H.COD_HOSPITAL = P.COD_HOSPITAL
GROUP BY H.COD_HOSPITAL;

-- 21 --
SELECT COUNT(P.DNI), M.ESPECIALIDAD
FROM PERSONAS P, MEDICOS M
WHERE P.COD_HOSPITAL = M.COD_HOSPITAL 
GROUP BY ESPECIALIDAD;

-- 22 --
SELECT COUNT(M.DNI), M.ESPECIALIDAD
FROM MEDICOS M
GROUP BY M.ESPECIALIDAD;


-- 23 --
SELECT H.NOMBRE 
FROM HOSPITALES H
ORDER BY H.NUM_PLAZAS DESC LIMIT 1;

-- 24 --
SELECT DISTINCT H.ESTANTERIA
FROM HERRAMIENTAS H
ORDER BY H.ESTANTERIA;

-- 25 --
SELECT COUNT(H.UNIDADES), H.ESTANTERIA
FROM HERRAMIENTAS H
GROUP BY H.ESTANTERIA;

-- 26 --
SELECT COUNT(H.UNIDADES), H.ESTANTERIA
FROM HERRAMIENTAS H
GROUP BY H.ESTANTERIA 
HAVING COUNT(H.UNIDADES) > 15;

-- 27 --
SELECT H.ESTANTERIA, SUM(H.UNIDADES)
FROM HERRAMIENTAS H
GROUP BY H.ESTANTERIA
ORDER BY MAX(H.UNIDADES) DESC LIMIT 1;

-- 28 --
-- oracle
SELECT DEPART.DEPT_NO, DEPART.DNOMBRE 
FROM DEPART, EMPLE
WHERE DEPART.DEPT_NO = EMPLE.DEPT_NO(+)
AND EMPLE.DEPTNO IS NULL;

-- 29 --
SELECT COUNT(E.EMP_NO), D.DEPT_NO
FROM DEPART D, EMPLE E
WHERE E.DEPT_NO = D.DEPT_NO 
GROUP BY D.DEPT_NO
UNION 
SELECT DEPART.DEPT_NO, DEPART.DNOMBRE 
FROM DEPART, EMPLE
WHERE DEPART.DEPT_NO = EMPLE.DEPT_NO(+)
AND EMPLE.DEPTNO IS NULL;

-- 30 --
SELECT SUM(E.SALARIO) AS SUMASALARIOS, D.DEPT_NO, D.DNOMBRE
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO = D.DEPT_NO 
GROUP BY D.DEPT_NO;

-- 31 --


-- 32 -- 
SELECT COUNT(M.DNI) AS NUMEROMEDICOS, H.COD_HOSPITAL, H.NOMBRE
FROM MEDICOS M, HOSPITALES H
WHERE M.COD_HOSPITAL = H.COD_HOSPITAL
GROUP BY H.COD_HOSPITAL;
WHERE M.COD_HOSPITAL = H.COD_HOSPITAL
