
-- 1

SELECT P.NOMBRE , P.APELLIDOS
FROM PERSONAS p 
WHERE EXTRACT(YEAR FROM P.FECHA_NACIMIENTO)>0079
ORDER BY P.FECHA_NACIMIENTO DESC;

-- 2

SELECT DISTINCT P.CODCABALLO
FROM PARTICIPACIONES p 
WHERE P.POSICIONFINAL < 4
ORDER BY P.CODCABALLO ASC;

-- 3

SELECT *
FROM CARRERAS c 
WHERE C.IMPORTEPREMIO > 50000;

-- 4

SELECT C.NOMBRE 
FROM CLIENTES c , APUESTAS a , CABALLOS c2 , PERSONAS p 
WHERE C.DNI = A.DNICLIENTE 
AND A.CODCABALLO = C2.CODCABALLO
AND C2.PROPIETARIO = P.CODIGO 
AND (P.NOMBRE  LIKE 'Jose'
OR P.NOMBRE  LIKE 'Inmaculada');

-- 5

SELECT C.NOMBRE , C.DNI 
FROM CLIENTES c 
WHERE C.NACIONALIDAD NOT IN ('Britanica','Escocesa');

-- 6

SELECT C.NOMBRE , C.PROPIETARIO 
FROM CABALLOS c 
WHERE EXTRACT(MONTH FROM C.FECHANACIMIENTO)=11
OR C.PESO >= 260
ORDER BY C.PROPIETARIO DESC, C.NOMBRE ASC;

-- 7

SELECT P.NOMBRE 
FROM PERSONAS p 
WHERE P.NOMBRE LIKE '%J%'
AND P.NOMBRE LIKE '%e%';

--8

SELECT DISTINCT P.CODCABALLO
FROM PARTICIPACIONES p
WHERE P.POSICIONFINAL = 1
GROUP BY P.CODCABALLO
HAVING COUNT(P.POSICIONFINAL)>1;

--9

SELECT * FROM (SELECT C.DNI, COUNT(A.DNICLIENTE)
				FROM CLIENTES c, APUESTAS a 
				WHERE C.DNI = A.DNICLIENTE
				GROUP BY C.DNI
				ORDER BY COUNT(A.DNICLIENTE) DESC)
WHERE ROWNUM = 1;

-- 10

SELECT P2.NOMBRE , COUNT(DISTINCT P.CODCABALLO)
FROM CABALLOS c , PARTICIPACIONES p, PERSONAS p2 
WHERE C.CODCABALLO = P.CODCABALLO
AND P.JOCKEY = P2.CODIGO 
GROUP BY P2.NOMBRE
ORDER BY COUNT(P.JOCKEY) DESC, P2.NOMBRE ASC;

-- 11

SELECT P.NOMBRE , P.APELLIDOS , C.NOMBRE 
FROM PERSONAS p , PARTICIPACIONES p2 , CABALLOS c 
WHERE P.CODIGO = P2.JOCKEY 
AND P2.CODCABALLO = C.CODCABALLO 
AND P2.POSICIONFINAL = 1;

-- 12

SELECT C.NOMBRECARRERA , P2.NOMBRE , A.IMPORTE 
FROM CARRERAS c , PARTICIPACIONES p , PERSONAS p2, APUESTAS a  
WHERE A.CODCARRERA = C.CODCARRERA 
AND C.CODCARRERA = P.CODCARRERA 
AND P.JOCKEY = P2.CODIGO 
AND A.IMPORTE > C.APUESTALIMITE ;

-- 13

SELECT P2.NOMBRE, P2.APELLIDOS, C.NOMBRE, COUNT(P.CODCABALLO) 
FROM CABALLOS c, PARTICIPACIONES p, PERSONAS p2 
WHERE C.CODCABALLO = P.CODCABALLO 
AND C.PROPIETARIO = P2.CODIGO
GROUP BY P2.NOMBRE, P2.APELLIDOS, C.NOMBRE
HAVING COUNT(P.CODCABALLO)>2;

-- 14

SELECT C2.NOMBRE , P3.NOMBRE, P2.NOMBRE, C.NOMBRECARRERA  
FROM PARTICIPACIONES p, CARRERAS c, CABALLOS c2 , PERSONAS p2, PERSONAS p3
WHERE P2.CODIGO = P.JOCKEY 
AND P.CODCARRERA = C.CODCARRERA 
AND P.CODCABALLO = C2.CODCABALLO 
AND C2.PROPIETARIO = P3.CODIGO
ORDER BY C.NOMBRECARRERA ASC, C2.NOMBRE ASC;

-- 15

SELECT C.NOMBRE , C.NACIONALIDAD
FROM CLIENTES c , APUESTAS a 
WHERE C.DNI = A.DNICLIENTE 
GROUP BY C.NOMBRE, C.NACIONALIDAD
HAVING SUM(A.IMPORTE) > 800;

-- 16 





