
--1 

SELECT * 
FROM (SELECT COUNT(E.NOMBRE_ESPECIE), A.NOMBRE, A.APELLIDOS 
					FROM EJEMPLARESMARIPOSAS e, AFICIONADOS a 
					WHERE E.DNI_CAPTURA=A.DNI 
					GROUP BY A.NOMBRE, A.APELLIDOS 
					ORDER BY COUNT(E.NOMBRE_ESPECIE)DESC) 
WHERE ROWNUM = 1;

-- 2
				
SELECT E.NOMBRE_ESPECIE 
FROM EJEMPLARESMARIPOSAS e 
WHERE E.TIPO_EJEMPLAR NOT IN (SELECT E2.TIPO_EJEMPLAR 
							FROM EJEMPLARESMARIPOSAS e2
							WHERE E2.TIPO_EJEMPLAR LIKE 'L');
						
-- 3
						
SELECT A.DNI, A.NOMBRE, A.APELLIDOS, A.ACTIVIDAD 
FROM AFICIONADOS a, COLECCIONES c 
WHERE A.DNI = C.DNI 
AND C.PRECIO_ESTIMADO = (SELECT MAX(C2.PRECIO_ESTIMADO)
			FROM COLECCIONES c2);
						
-- 4

SELECT A.DNI 
FROM AFICIONADOS a  
WHERE A.DNI IN (SELECT E.DNI_CAPTURA 
				FROM EJEMPLARESMARIPOSAS e
				WHERE E.NOMBRE_ESPECIE LIKE 'Saturnia Pavonia');
			
-- 5 

SELECT F.NOMBRE_FAMILIA, G.NOMBRE_GENERO, E.NOMBRE_ESPECIE 
FROM ESPECIES e , GENEROS g , FAMILIAS f 
WHERE F.NOMBRE_FAMILIA = G.NOMBRE_FAMILIA 
AND G.NOMBRE_GENERO = E.NOMBRE_GENERO 
AND E.NOMBRE_ESPECIE NOT IN (SELECT E2.NOMBRE_ESPECIE 
								FROM EJEMPLARESMARIPOSAS e2);
							
-- 6

SELECT *
FROM AFICIONADOS a 
WHERE A.DNI IN (SELECT E.DNI_CAPTURA 
					FROM EJEMPLARESMARIPOSAS e)
AND A.DNI NOT IN (SELECT C.DNI 
					FROM COLECCIONES c);
				
-- 7

SELECT DISTINCT(G.NOMBRE_FAMILIA)  
FROM GENEROS g , ESPECIES e 
WHERE G.NOMBRE_GENERO = E.NOMBRE_GENERO 
AND E.NOMBRE_ESPECIE IN (SELECT E2.NOMBRE_ESPECIE 
						FROM ESPECIES e2
						WHERE UPPER(E2.NOMBRE_ESPECIE) LIKE 'A%')
AND G.NOMBRE_FAMILIA IN (SELECT G2.NOMBRE_FAMILIA
						FROM ESPECIES e3, GENEROS g2
						WHERE G2.NOMBRE_GENERO = E3.NOMBRE_GENERO
						HAVING COUNT(E3.NOMBRE_ESPECIE) > 5
						GROUP BY G2.NOMBRE_FAMILIA);

-- 8

SELECT E.NOMBRE_ESPECIE, E.DNI_CAPTURA , E.DNI_COLECCION 
FROM EJEMPLARESMARIPOSAS e
WHERE E.TAMANO  = (SELECT MIN(E2.TAMANO) 
						FROM EJEMPLARESMARIPOSAS e2);
	
-- 9
					
SELECT DISTINCT(E2.NOMBRE_CIENTIFICO) 
FROM EJEMPLARESMARIPOSAS e, ESPECIES e2 
WHERE E2.NOMBRE_ESPECIE = E.NOMBRE_ESPECIE  
AND E.TAMANO > (SELECT AVG(NVL(E3.TAMANO,0))
				FROM EJEMPLARESMARIPOSAS e3);
			
-- 10

SELECT Z.PROVINCIA 
FROM ZONLOCPRO z 
WHERE Z.NOMBRE_ZONA NOT IN (SELECT E.NOMBRE_ZONA 
							FROM EJEMPLARESMARIPOSAS e);
						
-- 11
				
SELECT *
FROM (SELECT COUNT(E2.NOMBRE_ESPECIE), E2.SEXO
							FROM EJEMPLARESMARIPOSAS e2
							GROUP BY E2.SEXO
							ORDER BY COUNT(E2.NOMBRE_ESPECIE)) 
WHERE ROWNUM = 1;

-- 12

CREATE OR REPLACE VIEW EJEMPLARES
(NOMBRE_COMUN, NOMBRE_CIENTIFICO)
AS 
SELECT E.NOMBRE_ESPECIE, E.NOMBRE_CIENTIFICO 
FROM ESPECIES e, EJEMPLARESMARIPOSAS e2  
WHERE E.NOMBRE_ESPECIE = E2.NOMBRE_ESPECIE 
AND EXTRACT(YEAR FROM E2.FECHA_CAPTURA) IN (1996, 1997);

SELECT * FROM EJEMPLARES;

-- 13

SELECT COUNT(NOMBRE_ESPECIE), Z.LOCALIDAD, Z.PROVINCIA  
FROM EJEMPLARESMARIPOSAS e JOIN ZONLOCPRO z 
ON E.NOMBRE_ZONA = Z.NOMBRE_ZONA 
WHERE E.NOMBRE_ZONA IN (SELECT E2.NOMBRE_ZONA 
						FROM EJEMPLARESMARIPOSAS e2)
GROUP BY Z.LOCALIDAD, Z.PROVINCIA 
HAVING COUNT(NOMBRE_ESPECIE)>6
ORDER BY COUNT(NOMBRE_ESPECIE);

