-- 1.	Muestra el nombre de las empresas productoras de Huelva o Málaga ordenadas por el nombre 
-- en orden alfabético inverso.

SELECT E.NOMBRE_EMPRESA 
FROM EMPRESAPRODUCTORA e 
WHERE E.CIUDAD_EMPRESA LIKE 'Huelva'
OR e.CIUDAD_EMPRESA LIKE 'Málaga'
ORDER BY E.NOMBRE_EMPRESA DESC;

-- 2.	Mostrar los nombres de los destinos cuya ciudad contenga una b mayúscula o minúscula.

SELECT D.NOMBRE_DESTINO 
FROM DESTINO d 
WHERE upper(D.CIUDAD_DESTINO) LIKE '%B%';

-- 3.	Obtener el código de los residuos con una cantidad superior a 4 del constituyente 116.

SELECT RC.COD_RESIDUO 
FROM RESIDUO_CONSTITUYENTE rc 
WHERE RC.COD_CONSTITUYENTE = 116
AND RC.CANTIDAD > 4;

-- 4.	Muestra el tipo de transporte, los kilómetros y el coste de los traslados realizados en 
-- diciembre de 1994.

SELECT T.TIPO_TRANSPORTE , T.KMS , T.COSTE 
FROM TRASLADO t 
WHERE EXTRACT(YEAR FROM (T.FECHA_ENVIO)) = 1994
AND EXTRACT(MONTH FROM (T.FECHA_ENVIO))=12;

SELECT TIPO_TRANSPORTE, KMS, COSTE
FROM TRASLADO
WHERE TO_DATE(FECHA_ENVIO, 'MM/YYYY')=TO_DATE('12/1994', 'MM/YYYY');

-- 5.	Mostrar el código del residuo y el número de constituyentes de cada residuo.

SELECT RC.COD_RESIDUO , COUNT(RC.COD_CONSTITUYENTE)
FROM RESIDUO_CONSTITUYENTE rc 
GROUP BY RC.COD_RESIDUO ;

-- 6.	Mostrar la cantidad media de residuo vertida por las empresas durante el año 1994.

SELECT AVG(NVL(RE.CANTIDAD,0))
FROM RESIDUO_EMPRESA re 
WHERE EXTRACT (YEAR FROM (RE.FECHA)) = 1994;

-- 7.	Mostrar el mayor número de kilómetros de un traslado realizado el mes de marzo.

SELECT MAX(T.KMS)
FROM TRASLADO t 
WHERE EXTRACT (MONTH FROM (T.FECHA_ENVIO)) = 3; 

-- 8.	Mostrar el número de constituyentes distintos que genera cada empresa, 
-- mostrando también el nif de la empresa, para aquellas empresas que generen más de 4 constituyentes.

SELECT COUNT(DISTINCT(RC.COD_CONSTITUYENTE)), RE.NIF_EMPRESA 
FROM RESIDUO_EMPRESA re , RESIDUO r , RESIDUO_CONSTITUYENTE rc 
WHERE RE.COD_RESIDUO = R.COD_RESIDUO 
AND RE.COD_RESIDUO = R.COD_RESIDUO
HAVING COUNT(DISTINCT(RC.COD_CONSTITUYENTE))>4
GROUP BY RE.NIF_EMPRESA;

SELECT COUNT(DISTINCT RESIDUO_CONSTITUYENTE.COD_CONSTITUYENTE), RESIDUO_EMPRESA.NIF_EMPRESA
FROM RESIDUO_EMPRESA, RESIDUO, RESIDUO_CONSTITUYENTE
WHERE RESIDUO_EMPRESA.COD_RESIDUO = RESIDUO.COD_RESIDUO
AND RESIDUO.COD_RESIDUO = RESIDUO_CONSTITUYENTE.COD_RESIDUO
GROUP BY RESIDUO_EMPRESA.NIF_EMPRESA
HAVING COUNT(RESIDUO_CONSTITUYENTE.COD_CONSTITUYENTE)>4;

-- 9.	Mostrar el nombre de las diferentes empresas que han enviado residuos que contenga la palabra
--  metales en su descripción.

SELECT DISTINCT(E.NOMBRE_EMPRESA)
FROM RESIDUO r , RESIDUO_EMPRESA re ,EMPRESAPRODUCTORA e 
WHERE E.NIF_EMPRESA = RE.NIF_EMPRESA 
AND RE.COD_RESIDUO = R.COD_RESIDUO 
AND UPPER(R.OD_RESIDUO) LIKE '%METALES%';

-- 10.	Mostrar el número de envíos que se han realizado entre cada ciudad, 
--indicando también la ciudad origen y la ciudad destino

SELECT E2.CIUDAD_EMPRESA , D.CIUDAD_DESTINO, COUNT(T.NIF_EMPRESA)
FROM EMPRESAPRODUCTORA e2 , TRASLADO t , DESTINO d 
WHERE E2.NIF_EMPRESA  = T.NIF_EMPRESA  
AND D.COD_DESTINO = T.COD_DESTINO
GROUP BY E2.CIUDAD_EMPRESA, D.CIUDAD_DESTINO;

-- 11.	Mostrar el nombre de la empresa transportista que ha transportado para una empresa que esté 
-- en Málaga o en Huelva un residuo que contenga Bario o Lantano. Mostrar también la fecha del transporte.

SELECT DISTINCT(E.NOMBRE_EMPTRANSPORTE), T.FECHA_ENVIO  
FROM EMPRESATRANSPORTISTA e , TRASLADO t , EMPRESAPRODUCTORA e2, RESIDUO_EMPRESA re , RESIDUO r , RESIDUO_CONSTITUYENTE rc, CONSTITUYENTE c  
WHERE E.NIF_EMPTRANSPORTE = T.NIF_EMPTRANSPORTE 
AND T.NIF_EMPRESA = E2.NIF_EMPRESA 
AND E2.NIF_EMPRESA  = RE.NIF_EMPRESA 
AND RE.COD_RESIDUO = R.COD_RESIDUO 
AND R.COD_RESIDUO = RC.COD_RESIDUO 
AND RC.COD_CONSTITUYENTE = C.COD_CONSTITUYENTE 
AND (E2.CIUDAD_EMPRESA LIKE 'Málaga'
OR E2.CIUDAD_EMPRESA LIKE 'Huelva')
AND (C.NOMBRE_CONSTITUYENTE LIKE 'Bario'
OR C.NOMBRE_CONSTITUYENTE LIKE 'Lantano');

SELECT EMPRESATRANSPORTISTA.NOMBRE_EMPTRANSPORTE, TRASLADO.FECHA_ENVIO
FROM CONSTITUYENTE, RESIDUO_CONSTITUYENTE, RESIDUO, TRASLADO, EMPRESAPRODUCTORA, EMPRESATRANSPORTISTA
WHERE CONSTITUYENTE.COD_CONSTITUYENTE = RESIDUO_CONSTITUYENTE.COD_CONSTITUYENTE
AND RESIDUO_CONSTITUYENTE.COD_RESIDUO = RESIDUO.COD_RESIDUO
AND RESIDUO.COD_RESIDUO = TRASLADO.COD_RESIDUO
AND TRASLADO.NIF_EMPTRANSPORTE = EMPRESATRANSPORTISTA.NIF_EMPTRANSPORTE
AND TRASLADO.NIF_EMPRESA = EMPRESAPRODUCTORA.NIF_EMPRESA
AND EMPRESAPRODUCTORA.CIUDAD_EMPRESA  IN ('Málaga', 'Huelva')
AND CONSTITUYENTE.NOMBRE_CONSTITUYENTE IN ('Bario', 'Lantano');

-- 12.	Mostrar el coste por kilómetro del total de traslados encargados por la empresa productora Carbonsur.

SELECT SUM(T.KMS) AS TOTALKMS, SUM(T.COSTE) AS TOTALCOSTE, SUM(T.COSTE)/SUM(T.KMS)
FROM TRASLADO t , EMPRESAPRODUCTORA e 
WHERE E.NIF_EMPRESA = T.NIF_EMPRESA
AND E.NOMBRE_EMPRESA LIKE 'Carbonsur';

-- 13.	Mostrar el número de constituyentes de cada residuo.

SELECT COUNT(RC.COD_CONSTITUYENTE), RC.COD_RESIDUO 
FROM RESIDUO_CONSTITUYENTE rc 
GROUP BY RC.COD_RESIDUO;

-- 14.	Mostrar la descripción de los residuos y la fecha que se generó el residuo, para aquellos 
-- residuos que se han generado en los últimos 30 días por una empresa cuyo nombre tenga una c. 
-- La consulta debe ser válida para cualquier fecha y el listado debe aparecer ordenado por la 
-- descripción del residuo y la fecha.

SELECT RESIDUO.OD_RESIDUO, RESIDUO_EMPRESA.FECHA
FROM RESIDUO_EMPRESA, RESIDUO, EMPRESAPRODUCTORA
WHERE RESIDUO.COD_RESIDUO = RESIDUO_EMPRESA.COD_RESIDUO
AND RESIDUO_EMPRESA.NIF_EMPRESA = EMPRESAPRODUCTORA.NIF_EMPRESA
AND EMPRESAPRODUCTORA.NOMBRE_EMPRESA LIKE '%c%'
AND RESIDUO_EMPRESA.FECHA > (SYSDATE-30);
ORDER BY RESIDUO.OD_RESIDUO, RESIDUO_EMPRESA.FECHA;







