--1
BEGIN
 IF 10 > 5 THEN
 DBMS_OUTPUT.PUT_LINE ('Cierto');
 ELSE
 DBMS_OUTPUT.PUT_LINE ('Falso');
 END IF;
END;
-- EL RESULTADO ESPERADO ES: CIERTO
-- EL RESULTADO FINAL ES: CIERTO

-- 2
BEGIN
IF 10 > 5 AND 5 > 1 THEN
 DBMS_OUTPUT.PUT_LINE ('Cierto');
ELSE
 DBMS_OUTPUT.PUT_LINE ('Falso');
END IF;
END;
-- EL RESULTADO ESPERADO ES: CIERTO
-- EL RESULTADO FINAL ES: CIERTO

--3
BEGIN
IF 10 > 5 AND 5 > 50 THEN
 DBMS_OUTPUT.PUT_LINE ('Cierto');
ELSE
 DBMS_OUTPUT.PUT_LINE ('Falso');
END IF;
END;
--EL RESULTADO ESPERADO ES: FALSO
--EL RESULTADO FINAL ES: FALSO

--4
BEGIN
CASE
 WHEN 10 > 5 AND 5 > 50 THEN
 DBMS_OUTPUT.PUT_LINE ('Cierto');
 ELSE
 DBMS_OUTPUT.PUT_LINE ('Falso');
END CASE;
END;
--EL RESULTADO ESPERADO ES: FALSO
--EL RESULTADO FINAL ES: FALSO

--5
BEGIN
 FOR i IN 1..10 LOOP
 DBMS_OUTPUT.PUT_LINE (i);
 END LOOP;
END;
--EL RESULTADO ESPERADO ES: 1 2 3 4 5 6 7 8 9 10
-- EL RESULTADO FINAL ES: 1 2 3 4 5 6 7 8 9 10

--6
BEGIN
 FOR i IN REVERSE 1..10 LOOP
 DBMS_OUTPUT.PUT_LINE (i);
 END LOOP;
END;
-- EL RESULTADO ESPERADO ES: 10 9 8 7 6 5 4 3 2 1
-- EL RESULTADO FINAL ES: 10 9 8 7 6 5 4 3 2 1


--7
DECLARE
 num NUMBER(3) := 0;
BEGIN
 WHILE num<=100 LOOP
 DBMS_OUTPUT.PUT_LINE (num);
 num:= num+2;
 END LOOP;
END;
--EL RESULTADO ESPERADO ES: LOS NUMEROS DEL 1 AL 100 DE DOS EN DOS
-- EL RESULTADO FINAL ES: LOS NUMEROS DEL 1 AL 100 DE DOS EN DOS

--8
DECLARE
 num NUMBER(3) := 0;
BEGIN
 LOOP
 DBMS_OUTPUT.PUT_LINE (num);
 IF num > 100 THEN EXIT; END IF;
 num:= num+2;
 END LOOP;
END;
--EL RESULTADO ESPERADO ES: NUMEROS DEL 1 AL 100 DE DOS EN DOS
--EL RESULTADO FINAL ES: LO MISMO PERO HASTA 102

--9
DECLARE
 num NUMBER(3) := 0;
BEGIN
 LOOP
 DBMS_OUTPUT.PUT_LINE (num);
 EXIT WHEN num > 100;
 num:= num+2;
 END LOOP;
END;
--EL RESULTADO ESPERADO ES: IGUAL QUE EL 8
-- EL RESULTADO FINAL ES: IGUAL QUE EL 8
