DECLARE
  fecha DATE;
BEGIN
  SELECT sysdate INTO fecha FROM dual;
  dbms_output.put_line
  (
    to_CHAR(fecha,'day", "dd" de "month" de "yyyy", a las "hh24:mi:ss')
  );
END;

DECLARE
  fecha  DATE;
BEGIN
  DBMS_OUTPUT.PUT_LINE ('Salida de información');
  SELECT SYSDATE INTO fecha FROM DUAL;
  DBMS_OUTPUT.PUT_LINE ('Fecha:  ' || fecha);
END;

DECLARE
   A NUMBER := NULL;
   B NUMBER := 2;
   C NUMBER;

BEGIN

  IF  A IS NULL OR B IS NULL THEN
    C := 3;
  ELSIF A < B THEN
    C := 1;
  ELSE
    C := 2;
  END IF;
  DBMS_OUTPUT.PUT_LINE ('El valor de C es ' || C);

END;

DECLARE 
NOTA NUMBER(2);
BEGIN 
	NOTA :=8;

	IF NOTA >= 9 THEN
		DBMS_OUTPUT.PUT_LINE('SOBRESALIENTE');
	ELSIF NOTA >= 7 THEN
		DBMS_OUTPUT.PUT_LINE('NOTABLE');
	ELSIF NOTA=6 THEN 
		DBMS_OUTPUT.PUT_LINE('BIEN');
	ELSIF NOTA=5 THEN
		DBMS_OUTPUT.PUT_LINE('SUFICIENTE');
	ELSIF NOTA<5 AND NOTA >=0 THEN 
		DBMS_OUTPUT.PUT_LINE('INSUFUCIENTE');
	ELSE 
		DBMS_OUTPUT.PUT_LINE('NOTA NO VALIDA');
	END IF;
END;


CREATE TABLE TABLA_TEMP(
	NUMERO NUMBER(3)
);

DECLARE 
	NUMERO NUMBER(2) := 1;
BEGIN 
	LOOP 
		INSERT INTO TABLA_TEMP VALUES (NUMERO*10);
		EXIT WHEN NUMERO>=10;
		NUMERO:= NUMERO+1;
	END LOOP;
END;

SELECT * 
FROM TABLA_TEMP tt;


