CREATE TABLE CABALLO
(
	COD_CABALLO VARCHAR2(4),
	NOMBRE VARCHAR2(20) NOT NULL,
	PESO NUMBER(3),
	FECHA_NACIMIENTO DATE,
	PROPIETARIO VARCHAR2(25),
	NACIONALIDAD VARCHAR2(20),
	CONSTRAINT PK_CAB PRIMARY KEY (COD_CABALLO),
	CONSTRAINT CH1_CAB CHECK (PESO>240 AND PESO<300),
	CONSTRAINT CHK2_CAB CHECK (EXTRACT (YEAR FROM (FECHA_NACIMIENTO))>2000),
	CONSTRAINT CHK3_CAB CHECK (UPPER(NACIONALIDAD)=NACIONALIDAD)
);

CREATE TABLE CARRERAS
(
	COD_CARRERA VARCHAR2(4),
	FECHA_HORA DATE,
	IMPORTE_PREMIO NUMBER(6),
	APUESTA_LIMITE NUMBER(5,2),
	CONSTRAINT PK_CAR PRIMARY KEY (COD_CARRERA),
	CONSTRAINT CH1_CAR CHECK (APUESTA_LIMITE<20000),
	CONSTRAINT CH2_CAR CHECK (TO_CHAR (FECHA_HORA, 'HH24:MI')>='09:00' AND TO_CHAR(FECHA_HORA, 'HH24:MI')<='14:30')
);

CREATE TABLE PARTICIPACIONES
(
	COD_CABALLO VARCHAR2(4),
	COD_CARRERA VARCHAR2(4),
	DORSAL NUMBER(2) NOT NULL,
	JOCKEY VARCHAR2(10) NOT NULL,
	POSICION_FINAL NUMBER(2),
	CONSTRAINT PK_PAR PRIMARY KEY (COD_CARRERA, COD_CABALLO),
	CONSTRAINT FK_PAR FOREIGN KEY (COD_CABALLO) REFERENCES CABALLO(COD_CABALLO),
	CONSTRAINT FK2_PAR FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS(COD_CARRERA), 
	CONSTRAINT CHK1_PAR CHECK (POSICION_FINAL>0)
);

CREATE TABLE CLIENTES
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	CONSTRAINT PK_CLI PRIMARY KEY (DNI),
	CONSTRAINT CH1_CLI CHECK (REGEXP_LIKE(DNI,'^[0-9]{8}[A-Z]{1}$')),
	CONSTRAINT CH2_CLI CHECK (UPPER(NACIONALIDAD)=NACIONALIDAD)
);

CREATE TABLE APUESTAS
(
	DNI_CLIENTE VARCHAR2(10),
	COD_CABALLO VARCHAR2(4),
	COD_CARRERA VARCHAR2(4),
	IMPORTE NUMBER(6) DEFAULT 300 NOT NULL,
	TANTO_POR_UNO NUMBER(4,2),
	CONSTRAINT PK_APU PRIMARY KEY (DNI_CLIENTE, COD_CABALLO, COD_CARRERA),
	CONSTRAINT FK1_APU FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTES(DNI),
	CONSTRAINT FK2_APU FOREIGN KEY (COD_CABALLO) REFERENCES CABALLO(COD_CABALLO),
	CONSTRAINT FK3_APU FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS(COD_CARRERA),
	CONSTRAINT CH1_APU CHECK (TANTO_POR_UNO>1)
);


--2 inserta el registro
INSERT INTO CLIENTES VALUES ('12345678A', 'RODOLFO', 'ESCOCES');
INSERT INTO CABALLO VALUES ('A1', 'MANCHAS', 299,TO_DATE('22/07/2001','DD/MM/YYYY'),NULL, NULL);
INSERT INTO CARRERAS VALUES ('K4',TO_DATE('23/07/23 10:30','DD/MM/YY HH24:MI'),NULL, NULL);
INSERT INTO APUESTAS VALUES ('12345678A', 'A1','K4', 2000, 30.1);

--3 inscribe 2 caballos cuyo codigo es c6. inventate lo demas
INSERT INTO CABALLO VALUES ('J2','NEGRO',250,TO_DATE('20/06/2004','DD/MM/YYYY'),'MARCHENA','ARABE');
INSERT INTO CABALLO VALUES ('L6','CAMEL',280,TO_DATE('10/01/2009','DD/MM/YYYY'),'PEPITO','ESPAÑOLA');
INSERT INTO CARRERAS VALUES ('C6',TO_DATE('23/08/23 11:30','DD/MM/YY HH24:MI'), 305, 160);
INSERT INTO PARTICIPACIONES VALUES ('J2', 'C6', 11, 'ROCINANTE', NULL);
INSERT INTO PARTICIPACIONES VALUES ('L6', 'C6', 22, 'ROSALIA', NULL);

--4 inserta dos carreras con datos inventados
INSERT INTO CARRERAS VALUES ('P5',TO_DATE('23/07/22 12:30','DD/MM/YY HH24:MI'), 300, 150);
INSERT INTO CARRERAS VALUES ('H8',TO_DATE('10/07/23 9:30','DD/MM/YY HH24:MI'), 400, 100);

--5 quita el campo propietario de la tabla caballos
ALTER TABLE CABALLO DROP COLUMN PROPIETARIO;

--6 añadir restricciones
UPDATE PARTICIPACIONES SET JOCKEY='Rocinante' WHERE JOCKEY='ROCINANTE';
UPDATE PARTICIPACIONES SET JOCKEY='Rosalia' WHERE JOCKEY='ROSALIA';
ALTER TABLE PARTICIPACIONES ADD CONSTRAINT CH2_PAR CHECK (INITCAP(JOCKEY)=JOCKEY);
ALTER TABLE CARRERAS ADD CONSTRAINT CH_CAR CHECK (TO_CHAR (FECHA_HORA, 'DD/MM')>='10/03' OR TO_CHAR(FECHA_HORA, 'DD/MM')<='10/11');
ALTER TABLE CABALLO ADD CONSTRAINT CH4_CAB CHECK (NACIONALIDAD IN('ESPAÑOLA','BRITANICA','ARABE'));

SELECT * FROM CARRERAS
WHERE TO_CHAR (FECHA_HORA, 'DD/MM') >='10/03'
OR TO_CHAR(FECHA_HORA, 'DD/MM')<='10/11';

--6,2 borra las carreras en las que no hay caballos inscritos
DELETE FROM CARRERAS WHERE COD_CARRERA NOT IN (SELECT COD_CARRERA FROM PARTICIPACIONES);

--7 añade un campo llamado codigo en el campo clientes, que no permita valores nulos ni repetidos
CREATE SEQUENCE SQ_CL
START WITH 1
INCREMENT BY 1;
SELECT SQ_CL.nextval FROM DUAL;
ALTER TABLE CLIENTES ADD CODIGO VARCHAR2(4);
UPDATE CLIENTES SET CODIGO=SQ_CL.nextval;
ALTER TABLE CLIENTES MODIFY CODIGO VARCHAR2(4) UNIQUE;

 
--8 el codigo c6 es en realidad c66
INSERT INTO CARRERAS VALUES ('C66',TO_DATE('23/08/23 11:30','DD/MM/YY HH24:MI'), 305, 160);
UPDATE PARTICIPACIONES SET COD_CARRERA='C66' WHERE COD_CARRERA='C6';
DELETE FROM CARRERAS WHERE COD_CARRERA='C6'

--9 añade un campo llamado premio a las apuestas
ALTER TABLE APUESTAS ADD PREMIO VARCHAR2(10);
UPDATE FROM APUESTAS SET PREMIO=100;
 
--10 borra las tablas y datos con el numero menor de instrucciones posibles
TRUNCATE TABLE APUESTAS ON DELETE CONSTRAINT;
TRUNCATE TABLE CABALLO ON DELETE CONSTRAINT;
TRUNCATE TABLE CARRERAS ON DELETE CONSTRAINT;
TRUNCATE TABLE CLIENTE ON DELETE CONSTRAINT;
TRUNCATE TABLE PARTICIPACIONES ON DELETE CONSTRAINT;








