--1
ALTER TABLE ENFERMO ADD CONSTRAINT CH4_ENFERMO CHECK (SEXO IN('H','M'));

--3
ALTER TABLE ENFERMO MODIFY NSS VARCHAR(12);

--4
INSERT INTO MEDICO VALUES ('1', 'ALBERTO','FAM' ,'2',);
INSERT INTO ENFERMO VALUES ('1','53334E','MANUEL','H');
INSERT INTO ENFERMO VALUES ('2','3333R','MANUELA','M');

--5
INSERT INTO INGRESO VALUES('1','1','SYSDATE','','102');

--6
INSERT INTO VISITA VALUES('1','1','SYSDATE','FIEBRE');

--7
ALTER TABLE VISITA ADD FECHA_PROXIMA_VISITA;

--8
UPDATE ENFERMO SET NOMBRE='JOHN NIEVE' WHERE COD_INSCRIPCION='1';
UPDATE ENFERMO SET SEXO='H' WHERE COD_INSCRIPCION='1';

--9
DELETE FROM ENFERMO WHERE COD_INSCRIPCION IN ('1');

--10
DROP TABLE MEDICO CASCADE CONSTRAINT;
DROP TABLE ENFERMO CASCADE CONSTRAINT;
DROP TABLE HABITACION CASCADE CONSTRAINT;
DROP TABLE VISITA CASCADE CONSTRAINT;
DROP TABLE INGRESO CASCADE CONSTRAINT;

/*EJERCICIO 3
3.1 
NO, YA QUE LOS CREATE TABLE SI TIENEN AUTOCOMMIT PERO LOS INSERT TABLE NO, POR LO TANTO HABRIA QUE PONER COMMIT; DESPUÉS DE LOS INSERT Y EJECUTARLO

3.2
SI, YA QUE LOS CREATE TABLE TIENEN AUTOCOMMIT

3.3
SOLO PODRIAMOS EN EL CASO DE USAR SAVEPOINT EN EL PRINCIPIO DEL SCRIPT Y POSTERIORMENTE HACIENDO ROLLBACK A ESE SAVEPOINT. 
NO SE PODRIA CON COMMIT YA QUE EL ROLLBACK SOLO RETROCEDE UN COMMIT Y EN ESTE CASO EL ÚLTIMO COMMIT SE HIZO CUANDO CREAMOS LA TABLA CLIENTE

3.4
COMMIT; YA QUE LOS INSERT NO TIENEN AUTOCOMMIT COMO SI TENDRIAN LOS CREATE TABLE

3.5
SI, TENDRIAMOS QUE HACER ROLLBACK; PARA VOLVER AL ÚLTIMO COMMIT Y ASI TENDRIAMOS LA TABLA ANTES DE HABER BORRADO LOS DATOS

3.6
EL SAVEPOINT CONSISTE EN GUARDAR UN PUNTO DE RETORNO AL QUE PODEMOS VOLVER CUANDO UTILIZAMOS EL ROLLBACK nombre_savepoint.
*/
SAVEPOINT;

INSERT INTO MEDICO VALUES ('3', 'ALBERTO','FAM' ,'2');
SELECT COD_MEDICO FROM MEDICO WHERE COD_MEDICO IN ('3');

ROLLBACK;

SELECT COD_MEDICO FROM MEDICO WHERE COD_MEDICO IN ('3');

